version: 2.1
# Use a package of configuration called an orb.
orbs:
# Declare a dependency on the welcome-orb
  welcome: circleci/welcome=ob@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
    - image: circle/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
    - image: circle/node:13.8.0
    steps:
      - run: echo world
# Workflow
workflows:
  welcome: #the welcome dependency above
    #jobs the workflow will execute
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
           - print_hello
